baseURL: https://coderlytics.at/
languageCode: en-us
title: coderlytics.at
theme: hugo-profile

theme:
  disableThemeToggle: true
  defaultTheme: dark

contact:
  enable: false

footer:
  socialNetworks:
    github: https://github.com/coderlytics/
    linkedin: https://www.linkedin.com/in/michael-sieber/